### ISSUE TITLE
Upgrade MessagePack v0.7

### ISSUE THREAD

**Issue by muga** [treasure-data/embulk-output-td#2]
we should upgrade MessagePack v7 because of the performance improvement.

**Comment by xerial** [comment]
:+1:

**Comment by frsyuki** [comment]
Having MsgpackGZFileBuilder wrapper class seems also an unnecessary complexity.

**Comment by muga** [comment]
MessagePack v0.8 was released.

**Comment by muga** [comment]
Upgraded. Close this ticket.
