### ISSUE TITLE
The output schema order is not preserved.

### ISSUE THREAD

**Issue by xuantuan58** [treasure-data/embulk-output-td#91]
When running Embulk with input columns declaration: 
```
    ...
    columns:
      - {name: string_col, type: string}
      - {name: long_col_1, type: double}
      - {name: double_col, type: double}
      - {name: time_col, type: timestamp, format: '%Y-%m-%dT%H:%M:%S.%N'}
      - {name: json_col, type: json}
      - {name: bool_col, type: boolean}
```
The result output of this plugin produces columns alphabetitcally ordered by its columns name.
Even though, it's not so important in terms of a relational database. It's better to be fixed.

Expect: The output result columns order should be preserved (unchanged)

**Comment by nahi** [comment]
Could you put JIRA number for reference? Thanks!

**Comment by sakama** [comment]
@nahi This plugin is an OSS plugin. Do we use JIRA number for this?

**Comment by xuantuan58** [comment]
Already fixed
